name: 'Pico Build Action'
description: 'GitHub Action to build Pico projects using the Pico SDK.'
author: 'Olexandr Kolodkin'

inputs:
  install-path:
    description: 'Path to install the Pico SDK (default: <user home>/.pico-sdk).'
    required: false
    default: '${{ github.workspace }}/../../../.pico-sdk'

runs:
  using: composite
  steps:

    - name: 'Create install directory'
      shell: bash
      run: |
        mkdir -p ${{ inputs.install-path }}

    - name: 'Install pre-requisites'
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: 'Get Pico SDK'
      shell: bash
      run: |
        cd ${{ inputs.install-path }}
        git config --global advice.detachedHead false
        git clone --branch=2.2.0 --depth=1 https://github.com/raspberrypi/pico-sdk.git
        git -C pico-sdk submodule update --init --recursive
        echo "PICO_SDK_PATH=$(realpath ${{ inputs.install-path }}/pico-sdk)" >> $GITHUB_ENV

    - name: 'Install picotool'
      if: runner.os == 'Linux'
      shell: bash
      run: |
        curl -L https://github.com/raspberrypi/pico-sdk-tools/releases/download/v2.0.0-5/picotool-2.0.0-x86_64-lin.tar.gz | tar xz -C ${{ inputs.install-path }}
        echo "$(realpath ${{ inputs.install-path }}/picotool)" >> $GITHUB_PATH

    - name: 'Install pico-sdk-tools'
      if: runner.os == 'Linux'
      shell: bash
      run: |
        curl -L https://github.com/raspberrypi/pico-sdk-tools/releases/download/v2.0.0-5/pico-sdk-tools-2.0.0-x86_64-lin.tar.gz | tar xz -C ${{ inputs.install-path }}
        echo "$(realpath ${{ inputs.install-path }}/pioasm)" >> $GITHUB_PATH

    - name: 'Install risc-v toolchain'
      if: runner.os == 'Linux'
      shell: bash
      run: |
        mkdir -p ${{ inputs.install-path }}/riscv-toolchain
        curl -L https://github.com/raspberrypi/pico-sdk-tools/releases/download/v2.0.0-5/riscv-toolchain-14-x86_64-lin.tar.gz | tar xz -C ${{ inputs.install-path }}/riscv-toolchain
        echo "$(realpath ${{ inputs.install-path }}/riscv-toolchain)" >> $GITHUB_PATH

    - name: 'Install arm-none-eabi toolchain'
      if: runner.os == 'Linux'
      shell: bash
      run: |
        mkdir -p ${{ inputs.install-path }}/arm-gnu-toolchain
        curl -L https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz | tar xJC ${{ inputs.install-path }}/arm-gnu-toolchain --strip-components=1
        echo "$(realpath ${{ inputs.install-path }}/arm-gnu-toolchain)" >> $GITHUB_PATH

    - name: 'Print sdk installation path as tree'
      shell: bash
      run: |
        echo "Pico SDK installed at: ${{ inputs.install-path }}"
        tree -L 2 ${{ inputs.install-path }}

    - name: 'Print environment variables'
      shell: bash
      run: |
        echo "PICO_SDK_PATH=$PICO_SDK_PATH"
        echo "PATH=$PATH"

    - name: 'Print tools versions'
      shell: bash
      run: |
        git --version
        cmake --version
        picotool version
        pioasm --help # pioasm doesn't have a version flag, so just run it to confirm it's working
        arm-none-eabi-gcc --version
        riscv64-unknown-elf-gcc --version
