name: Test Action

on:
  push:
    branches:
      - main
      - 2.2.0
  pull_request:
    branches:
      - main
      - 2.2.0
  workflow_dispatch:

jobs:
  test-action:
    name: Test Pico Build Action
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout action repository
        uses: actions/checkout@v6
      
      - name: Test action with default install path
        uses: ./
        with:
          source-dir: 'test-project'
  